export enum RequestEnvironment {
  TEST = 'TEST',
  LIVE = 'LIVE',
}

export enum BasicStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum TransactionSource {
  COLLECTION_FEE = 'COLLECTION_FEE',
  WALLET_FUNDING = 'WALLET_FUNDING',
  TRANSFER = 'TRANSFER',
  BILLS_PAYMENT = 'BILLS_PAYMENT',
  BILLS_PAYMENT_FEE = 'BILLS_PAYMENT_FEE',
  TRANSFER_FEE = 'TRANSFER_FEE',
  STAMP_DUTY = 'STAMP_DUTY',
  CHECKOUT_INVOICE = 'CHECKOUT_INVOICE',
}

export enum CollectionChannel {
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT_COLLECTION',
  POS = 'POS_COLLECTION',
  DEBIT_CARD = 'DEBIT_CARD_COLLECTION',
  CLEVIX_WALLET = 'CLEVIX_WALLET',
  USSD = 'USSD',
}

export enum IncomingPaymentSource {
  VIRTUAL_ACCOUNT_COLLECTION = 'VIRTUAL_ACCOUNT_COLLECTION',
  CLEVIX_WALLET = 'CLEVIX_WALLET',
  POS_COLLECTION = 'POS_COLLECTION',
  USSD = 'USSD',
  DEBIT_CARD = 'DEBIT_CARD',
}

export enum PosChargePurpose {
  WALLET_FUNDING = 'WALLET_FUNDING',
  PURCHASE = 'PURCHASE',
}

export enum CollectionSource {
  POS = 'POS',
  DEBIT_MANDATES = 'DEBIT_MANDATES',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
  CARD = 'CARD',
}

export enum LedgerEntryDirection {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum TransactionStatus {
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum TransactionSettlementStatus {
  UNSETTLED = 'UNSETTLED',
  SETTLED = 'SETTLED',
  REVERSED = 'REVERSED',
}

export enum TransactionRiskStatus {
  CLEAR = 'CLEAR',
  HELD = 'HELD',
  DISPUTED = 'DISPUTED',
}

export enum WalletTransactionType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}

export enum WalletTransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum WalletTransactionSource {
  COLLECTION = 'COLLECTION',
  SETTLEMENT = 'SETTLEMENT',
  PAYOUT = 'PAYOUT',
  FEE = 'FEE',
  REVERSAL = 'REVERSAL',
  ADJUSTMENT = 'ADJUSTMENT',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
}

export enum JobQueueList {
  MONEY_TRANSFER_PROCESSOR = 'MONEY_TRANSFER_PROCESSOR',
}

export enum WebhookAuthType {
  API_KEY = 'API_KEY',

  NO_AUTH = 'NO_AUTH',

  BEARER_TOKEN = 'BEARER_TOKEN',
}

export enum OrganizationType {
  PRIVATE_COMPANY = 'PRIVATE_COMPANY',
  GOVERNMENT = 'GOVERNMENT',
  EDUCATIONAL = 'EDUCATIONAL',
  NGO = 'NGO',
  SOLE_PROPRIETOR = 'SOLE_PROPRIETOR',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum KycStatus {
  APPROVED = 'APPROVED',
  IN_REVIEW = 'IN_REVIEW',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}

export enum TaxCollectionMode {
  PLATFORM_WITHHELD = 'PLATFORM_WITHHELD',
  MERCHANT_REMITTED = 'MERCHANT_REMITTED',
  GOVERNMENT_DIRECT = 'GOVERNMENT_DIRECT',
}

export enum TaxPayer {
  CUSTOMER = 'CUSTOMER',
  BUSINESS = 'BUSINESS',
}

export enum ActionOwner {
  USER = 'USER',
  BUSINESS = 'BUSINESS',
}

export enum TokenType {
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
}

export enum TokenNotificationType {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  BOTH = 'BOTH',
}
