export enum RequestEnvironment {
  TEST = 'TEST',
  LIVE = 'LIVE',
}

export enum BasicStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum TransactionSource {
  COLLECTION_FEE = 'COLLECTION_FEE',
  VIRTUAL_ACCOUNT_COLLECTION = 'VIRTUAL_ACCOUNT_COLLECTION',
  POS_COLLECTION = 'POS_COLLECTION',
  DEBIT_CARD_COLLECTION = 'DEBIT_CARD_COLLECTION',
  TRANSFER = 'TRANSFER',
  BILLS_PAYMENT = 'BILLS_PAYMENT',
  BILLS_PAYMENT_FEE = 'BILLS_PAYMENT_FEE',
  TRANSFER_FEE = 'TRANSFER_FEE',
  STAMP_DUTY = 'STAMP_DUTY',
  CHECKOUT_INVOICE = 'CHECKOUT_INVOICE',
}

export enum IncomingPaymentSource {
  VIRTUAL_ACCOUNT_COLLECTION = 'VIRTUAL_ACCOUNT_COLLECTION',
  CLEVIX_WALLET = 'CLEVIX_WALLET',
  POS_COLLECTION = 'POS_COLLECTION',
  USSD = 'USSD',
  DEBIT_CARD = 'DEBIT_CARD',
}

export enum PosChargePurpose {
  WALLET_FUNDING = 'WALLET_FUNDING',
  PURCHASE = 'PURCHASE',
}

export enum CollectionSource {
  POS = 'POS',
  DEBIT_MANDATES = 'DEBIT_MANDATES',
  VIRTUAL_ACCOUNT = 'VIRTUAL_ACCOUNT',
  CARD = 'CARD',
}

export enum LedgerEntryDirection {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum TransactionStatus {
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum TransactionSettlementStatus {
  UNSETTLED = 'UNSETTLED',
  SETTLED = 'SETTLED',
  REVERSED = 'REVERSED',
}

export enum TransactionRiskStatus {
  CLEAR = 'CLEAR',
  HELD = 'HELD',
  DISPUTED = 'DISPUTED',
}

export enum JobQueueList {
  MONEY_TRANSFER_PROCESSOR = 'MONEY_TRANSFER_PROCESSOR',
}

export enum WebhookAuthType {
  API_KEY = 'API_KEY',

  NO_AUTH = 'NO_AUTH',

  BEARER_TOKEN = 'BEARER_TOKEN',
}

export enum OrganizationType {
  PRIVATE_COMPANY = 'PRIVATE_COMPANY',
  GOVERNMENT = 'GOVERNMENT',
  EDUCATIONAL = 'EDUCATIONAL',
  NGO = 'NGO',
  SOLE_PROPRIETOR = 'SOLE_PROPRIETOR',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum KycStatus {
  APPROVED = 'APPROVED',
  IN_REVIEW = 'IN_REVIEW',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}
