import { MigrationInterface, QueryRunner } from "typeorm";

export class V11786474462199 implements MigrationInterface {
    name = 'V11786474462199'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."business_documents_verificationstatus_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "business_documents" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "businessDocumentId" uuid NOT NULL DEFAULT uuid_generate_v4(), "file" character varying NOT NULL, "businessId" uuid NOT NULL, "documentName" character varying NOT NULL, "verificationStatus" "public"."business_documents_verificationstatus_enum" NOT NULL DEFAULT 'PENDING', "rejectionReason" character varying, "verifiedBy" character varying, "verifiedAt" TIMESTAMP, CONSTRAINT "PK_a73768974e3c03306824d09ac09" PRIMARY KEY ("businessDocumentId"))`);
        await queryRunner.query(`CREATE TABLE "local_governments" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "lgId" uuid NOT NULL DEFAULT uuid_generate_v4(), "stateId" uuid NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4addc91b0b927a3e9cad08bff3b" PRIMARY KEY ("lgId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5df41035b36fce1e68f1ff5fb4" ON "local_governments"  ("stateId", "name") `);
        await queryRunner.query(`CREATE TABLE "states" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "stateId" uuid NOT NULL DEFAULT uuid_generate_v4(), "countryId" uuid NOT NULL, "name" character varying NOT NULL, "code" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_e54e3519e287181c0398c7667ab" PRIMARY KEY ("stateId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1e0f02ae40fe2ea4da13b8d460" ON "states"  ("countryId", "name") `);
        await queryRunner.query(`CREATE TABLE "countries" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "countryId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "countryCode" character varying NOT NULL, "phoneCode" character varying, "currency" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c9ebef6aac022e54b1b01c8f824" PRIMARY KEY ("countryId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fa1376321185575cf2226b1491" ON "countries"  ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2dd5aa96583bb914f7bbdb3e7b" ON "countries"  ("countryCode") `);
        await queryRunner.query(`CREATE TYPE "public"."businesses_kycstatus_enum" AS ENUM('APPROVED', 'IN_REVIEW', 'REJECTED', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "businesses" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "businessId" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessIdentifier" character varying NOT NULL, "environment" character varying NOT NULL, "businessName" character varying NOT NULL, "countryId" uuid NOT NULL, "stateId" uuid, "kycStatus" "public"."businesses_kycstatus_enum" NOT NULL DEFAULT 'PENDING', "isActive" boolean NOT NULL DEFAULT false, "lgId" uuid, "businessPhone" character varying NOT NULL, "businessAddress" character varying NOT NULL, CONSTRAINT "PK_76874e4d78318eb5a3af1c21125" PRIMARY KEY ("businessId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ac3ab3b9418ea0499239cdd82" ON "businesses"  ("businessIdentifier") `);
        await queryRunner.query(`CREATE TYPE "public"."business_information_businesstype_enum" AS ENUM('PRIVATE_COMPANY', 'GOVERNMENT', 'EDUCATIONAL', 'NGO', 'SOLE_PROPRIETOR')`);
        await queryRunner.query(`CREATE TABLE "business_information" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "businessInformationId" uuid NOT NULL DEFAULT uuid_generate_v4(), "regNumber" character varying, "addressOne" character varying NOT NULL, "businessId" uuid NOT NULL, "addressTwo" character varying, "businessType" "public"."business_information_businesstype_enum" NOT NULL, "businessEmail" character varying NOT NULL, "city" character varying NOT NULL, CONSTRAINT "REL_39eb4eae73174c9cdbf595b868" UNIQUE ("businessId"), CONSTRAINT "PK_879dfe6b55bf7274d78810cc99b" PRIMARY KEY ("businessInformationId"))`);
        await queryRunner.query(`CREATE TYPE "public"."business_representatives_verificationstatus_enum" AS ENUM('PENDING', 'VERIFIED', 'REJECTED')`);
        await queryRunner.query(`CREATE TYPE "public"."business_representatives_identificationtype_enum" AS ENUM('NIN', 'BVN', 'INTERNATIONAL_PASSPORT', 'DRIVERS_LICENSE', 'VOTERS_CARD', 'OTHERS')`);
        await queryRunner.query(`CREATE TABLE "business_representatives" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "businessRepresentativeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "middleName" character varying, "email" character varying NOT NULL, "verificationStatus" "public"."business_representatives_verificationstatus_enum" NOT NULL DEFAULT 'PENDING', "rejectionReason" character varying, "phoneNumber" character varying NOT NULL, "role" character varying NOT NULL, "identificationType" "public"."business_representatives_identificationtype_enum" NOT NULL, "identificationNumber" character varying NOT NULL, "identificationDocument" character varying, "isPrimaryContact" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_0fa679a6c4c7f115aa0578ff5f1" PRIMARY KEY ("businessRepresentativeId"))`);
        await queryRunner.query(`CREATE TABLE "users" ("userId" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "activeBusinessId" uuid, "email" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "dialCode" character varying NOT NULL, "password" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleteAt" TIMESTAMP, CONSTRAINT "PK_8bf09ba754322ab9c22a215c919" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "permissionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_b4b17d691e3c22be36b2b9f355a" PRIMARY KEY ("permissionId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_017943867ed5ceef9c03edd974" ON "permissions"  ("key") `);
        await queryRunner.query(`CREATE TABLE "business_role_permissions" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "rolePermissionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_58307edf209d85dc390122e754f" PRIMARY KEY ("rolePermissionId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_30d94f2130ca24db97d9d52a26" ON "business_role_permissions"  ("roleId", "permissionId") `);
        await queryRunner.query(`CREATE TABLE "business_roles" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "roleId" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "isDefault" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_989fb21d93df158d8fd37d6e2a4" PRIMARY KEY ("roleId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3be415f19162963a266cac5a92" ON "business_roles"  ("businessId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."business_members_status_enum" AS ENUM('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED')`);
        await queryRunner.query(`CREATE TABLE "business_members" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "businessMemberId" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "status" "public"."business_members_status_enum" NOT NULL, "invitedByUserId" uuid, "acceptedAt" TIMESTAMP, CONSTRAINT "PK_5bbb231400ae258eb419855f1dc" PRIMARY KEY ("businessMemberId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_419792071f3f329280668ca950" ON "business_members"  ("businessId", "userId") `);
        await queryRunner.query(`CREATE TABLE "platform_fee_configuration" ("platformFeeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying NOT NULL, "providerPercentageFee" numeric NOT NULL DEFAULT '0', "providerPercentageFeeCap" numeric NOT NULL DEFAULT '0', "platformPercentageFee" numeric NOT NULL DEFAULT '0', "PlatformPercentageFeeCap" numeric NOT NULL DEFAULT '0', "providerflatFee" integer NOT NULL DEFAULT '0', "platformflatFee" integer NOT NULL DEFAULT '0', "useFlatFee" boolean NOT NULL DEFAULT false, "feeSource" character varying NOT NULL, CONSTRAINT "PK_c1e4eff84d4d7a1a48c1fc67aa8" PRIMARY KEY ("platformFeeId"))`);
        await queryRunner.query(`CREATE TABLE "business_fee_configuration" ("businessFeeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" uuid NOT NULL, "platformFeeId" uuid NOT NULL, "businessPercentageFee" numeric NOT NULL DEFAULT '0', "businessPercentageFeeCap" numeric NOT NULL DEFAULT '0', "businessFeeFlat" integer NOT NULL DEFAULT '0', "useFlatFee" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_29677ffdec718e892d09ee99ad3" PRIMARY KEY ("businessFeeId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6b33ba5b78af59608a0877f829" ON "business_fee_configuration"  ("businessId", "platformFeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."keys_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "keys" ("businessId" uuid NOT NULL, "environment" "public"."keys_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "keyId" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientId" character varying NOT NULL, "keyHash" character varying NOT NULL, CONSTRAINT "PK_6fb50ee91fbec940b37a887623d" PRIMARY KEY ("keyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18d316d3f20936e7a518d696ff" ON "keys"  ("clientId") `);
        await queryRunner.query(`CREATE TYPE "public"."ledger_transactions_status_enum" AS ENUM('PENDING', 'POSTED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "ledger_transactions" ("environment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ledgerTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "transactionType" character varying NOT NULL, "status" "public"."ledger_transactions_status_enum" NOT NULL, "description" character varying, "metadata" jsonb, CONSTRAINT "PK_9bfb7efcdf2716ed53770e50c0c" PRIMARY KEY ("ledgerTransactionId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d87ef09b49fbca993d4370616a" ON "ledger_transactions"  ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."ledger_entries_direction_enum" AS ENUM('DEBIT', 'CREDIT')`);
        await queryRunner.query(`CREATE TABLE "ledger_entries" ("environment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ledgerEntryId" uuid NOT NULL DEFAULT uuid_generate_v4(), "ledgerTransactionId" uuid NOT NULL, "ledgerAccountId" uuid NOT NULL, "direction" "public"."ledger_entries_direction_enum" NOT NULL, "amount" bigint NOT NULL, "currency" character varying(3) NOT NULL, "memo" character varying, CONSTRAINT "PK_c2958cfcb7128ff1bc8e32c72ce" PRIMARY KEY ("ledgerEntryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_451dcefe42673ec42abb693d33" ON "ledger_entries"  ("ledgerTransactionId", "ledgerAccountId", "direction") `);
        await queryRunner.query(`CREATE TABLE "ledger_accounts" ("environment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "ledgerAccountId" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerType" character varying NOT NULL, "ownerId" character varying, "accountType" character varying NOT NULL, "balance" bigint NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b72876a2fcf9f430a282484b616" PRIMARY KEY ("ledgerAccountId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_12a06b7faf8dc50c2a7590e603" ON "ledger_accounts"  ("ownerType", "ownerId", "accountType", "currency", "environment") `);
        await queryRunner.query(`CREATE TYPE "public"."organisation_payment_rules_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "organisation_payment_rules" ("businessId" uuid NOT NULL, "environment" "public"."organisation_payment_rules_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "paymentRuleId" uuid NOT NULL DEFAULT uuid_generate_v4(), "chargeFee" boolean NOT NULL DEFAULT false, "acceptPartPayment" boolean NOT NULL, "invoiceExpiryMinutes" integer, "currencyCode" character varying NOT NULL, CONSTRAINT "PK_f01d8ffcd9c7229235954f99249" PRIMARY KEY ("paymentRuleId"))`);
        await queryRunner.query(`CREATE TYPE "public"."organisation_form_options_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "organisation_form_options" ("businessId" uuid NOT NULL, "environment" "public"."organisation_form_options_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "optionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying NOT NULL, "value" character varying NOT NULL, "sequenceNo" character varying NOT NULL, "customFormFormId" uuid, CONSTRAINT "PK_86f811ae3f9c724fa5bf3460240" PRIMARY KEY ("optionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."organisation_custom_forms_formtype_enum" AS ENUM('text', 'email', 'number', 'tel', 'date', 'checkbox', 'radio', 'select', 'textarea', 'file')`);
        await queryRunner.query(`CREATE TYPE "public"."organisation_custom_forms_ownertype_enum" AS ENUM('service', 'platform')`);
        await queryRunner.query(`CREATE TABLE "organisation_custom_forms" ("environment" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "formId" uuid NOT NULL DEFAULT uuid_generate_v4(), "formType" "public"."organisation_custom_forms_formtype_enum" NOT NULL, "formKey" character varying NOT NULL, "formLabel" character varying NOT NULL, "formLength" character varying NOT NULL, "sequenceNo" character varying NOT NULL, "required" character varying NOT NULL, "isMandatory" boolean NOT NULL DEFAULT false, "ownerType" "public"."organisation_custom_forms_ownertype_enum" NOT NULL, "ownerId" uuid, CONSTRAINT "PK_b380b72fdc12d4a1948596868fb" PRIMARY KEY ("formId"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payment_transactions_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payment_transactions_method_enum" AS ENUM('POS', 'TRANSFER', 'CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_payment_transactions_paymentstatus_enum" AS ENUM('INITIATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "invoice_payment_transactions" ("businessId" uuid NOT NULL, "environment" "public"."invoice_payment_transactions_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "invoicePaymentTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "method" "public"."invoice_payment_transactions_method_enum" NOT NULL, "paymentStatus" "public"."invoice_payment_transactions_paymentstatus_enum" NOT NULL DEFAULT 'PENDING', "transactionId" uuid, "invoiceReference" character varying, CONSTRAINT "PK_73993f175db4956d075dc8c070d" PRIMARY KEY ("invoicePaymentTransactionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."tax_configurations_collectionmode_enum" AS ENUM('PLATFORM_WITHHELD', 'MERCHANT_REMITTED', 'GOVERNMENT_DIRECT')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_configurations_payer_enum" AS ENUM('CUSTOMER', 'BUSINESS')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_configurations_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "tax_configurations" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "taxId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "rate" numeric(10,4) NOT NULL DEFAULT '0', "collectionMode" "public"."tax_configurations_collectionmode_enum" NOT NULL DEFAULT 'PLATFORM_WITHHELD', "payer" "public"."tax_configurations_payer_enum" NOT NULL DEFAULT 'CUSTOMER', "status" "public"."tax_configurations_status_enum" NOT NULL DEFAULT 'ACTIVE', "countryId" uuid NOT NULL, "stateId" uuid, "lgId" uuid, CONSTRAINT "PK_7512e009268bcc5efb3f77490a8" PRIMARY KEY ("taxId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a45be23c6ab4d0aaa1076e66a4" ON "tax_configurations"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_47464f060473bf1af7084c05f9" ON "tax_configurations"  ("collectionMode") `);
        await queryRunner.query(`CREATE INDEX "IDX_6f6640e3b199ca3435df76c52d" ON "tax_configurations"  ("lgId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a507a3b9751e4a27a319bb20d" ON "tax_configurations"  ("stateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f3ae6d1a0651de752624707f2" ON "tax_configurations"  ("countryId") `);
        await queryRunner.query(`CREATE TYPE "public"."service_items_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "service_items" ("businessId" uuid NOT NULL, "environment" "public"."service_items_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "itemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "fixedPrice" boolean NOT NULL DEFAULT false, "fixedAmount" bigint, "settlementAccountId" character varying NOT NULL, "taxId" uuid, "serviceServiceId" uuid, CONSTRAINT "PK_a3bd4de39854b2ba71bd6d11daa" PRIMARY KEY ("itemId"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_items_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("businessId" uuid NOT NULL, "environment" "public"."invoice_items_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "invoiceItemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" bigint NOT NULL, "baseAmount" bigint NOT NULL, "taxAmount" bigint NOT NULL DEFAULT '0', "taxId" uuid, "invoiceId" uuid NOT NULL, "itemId" uuid NOT NULL, CONSTRAINT "PK_6c077fd4d8a7f65127101d40ff2" PRIMARY KEY ("invoiceItemId"))`);
        await queryRunner.query(`CREATE TYPE "public"."organisation_invoices_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."organisation_invoices_status_enum" AS ENUM('pending', 'paid', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."organisation_invoices_redemptionstatus_enum" AS ENUM('NOT_USED', 'REDEEMED')`);
        await queryRunner.query(`CREATE TABLE "organisation_invoices" ("businessId" uuid NOT NULL, "environment" "public"."organisation_invoices_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "invoiceId" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "merchantReference" character varying, "payerFullName" character varying NOT NULL, "payerEmail" character varying NOT NULL, "phoneNumber" character varying, "formDetails" jsonb NOT NULL, "amount" bigint NOT NULL, "currencyCode" character varying NOT NULL, "status" "public"."organisation_invoices_status_enum" NOT NULL DEFAULT 'pending', "redemptionStatus" "public"."organisation_invoices_redemptionstatus_enum", "paidAt" TIMESTAMP WITH TIME ZONE, "redeemedAt" TIMESTAMP WITH TIME ZONE, "redeemedBy" uuid, "expiresAt" TIMESTAMP WITH TIME ZONE, "serviceId" uuid NOT NULL, CONSTRAINT "UQ_441baa7b5d7ad01fc55e4878844" UNIQUE ("reference"), CONSTRAINT "PK_5843a89d8a85f76212f83bf51a9" PRIMARY KEY ("invoiceId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_32365b6733883d0cec79c0938a" ON "organisation_invoices"  ("businessId", "merchantReference") WHERE "merchantReference" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."organization_services_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "organization_services" ("businessId" uuid NOT NULL, "environment" "public"."organization_services_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "serviceId" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceName" character varying NOT NULL, "apiInitiationOnly" boolean NOT NULL DEFAULT false, "customerPayForListOfItems" boolean NOT NULL DEFAULT false, "requiredRedemption" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "paymentRuleId" uuid, CONSTRAINT "REL_cf970eb883389312269fa0e76e" UNIQUE ("paymentRuleId"), CONSTRAINT "PK_3db01614f39dbe5a2129794c0e3" PRIMARY KEY ("serviceId"))`);
        await queryRunner.query(`CREATE TYPE "public"."business_settlement_configs_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."business_settlement_configs_settlementlocation_enum" AS ENUM('WALLET', 'BANK')`);
        await queryRunner.query(`CREATE TYPE "public"."business_settlement_configs_paymentsource_enum" AS ENUM('VIRTUAL_ACCOUNT_COLLECTION', 'CLEVIX_WALLET', 'POS_COLLECTION', 'USSD', 'DEBIT_CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."business_settlement_configs_settlementtype_enum" AS ENUM('INSTANT', 'T+1')`);
        await queryRunner.query(`CREATE TABLE "business_settlement_configs" ("businessId" uuid NOT NULL, "environment" "public"."business_settlement_configs_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "businessSettelementConfig" uuid NOT NULL DEFAULT uuid_generate_v4(), "settlementLocation" "public"."business_settlement_configs_settlementlocation_enum" NOT NULL, "paymentSource" "public"."business_settlement_configs_paymentsource_enum" NOT NULL, "settlementType" "public"."business_settlement_configs_settlementtype_enum" NOT NULL, CONSTRAINT "CHK_568ff5d5efb2b5a0dd76a10e86" CHECK ("settlementType" != 'INSTANT' OR "settlementLocation" = 'WALLET'), CONSTRAINT "PK_0f46b1253101568981f4704a73b" PRIMARY KEY ("businessSettelementConfig"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5e2ba1a7e2a123c0382ff596ba" ON "business_settlement_configs"  ("businessId", "paymentSource") `);
        await queryRunner.query(`CREATE TABLE "banks" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "bankId" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "bankCode" character varying NOT NULL, "countryId" uuid NOT NULL, CONSTRAINT "PK_48859ae361135876ed792027a53" PRIMARY KEY ("bankId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e608c72b9dbc500479e821b695" ON "banks"  ("countryId", "bankCode") `);
        await queryRunner.query(`CREATE TYPE "public"."SettlementBankAccounts_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "SettlementBankAccounts" ("businessId" uuid NOT NULL, "environment" "public"."SettlementBankAccounts_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "bankAccountId" uuid NOT NULL DEFAULT uuid_generate_v4(), "isPrimary" boolean NOT NULL DEFAULT false, "accountNumber" character varying NOT NULL, "accountName" character varying NOT NULL, "providerbankId" uuid NOT NULL, CONSTRAINT "PK_d2e74e7fee4fce991395cac061c" PRIMARY KEY ("bankAccountId"))`);
        await queryRunner.query(`CREATE TYPE "public"."wallets_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "wallets" ("businessId" uuid NOT NULL, "environment" "public"."wallets_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "walletId" uuid NOT NULL DEFAULT uuid_generate_v4(), "balance" bigint NOT NULL DEFAULT '0', "currency" character varying NOT NULL, CONSTRAINT "PK_8e246dfcb84930971b5300d8cad" PRIMARY KEY ("walletId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0dc7c27ca503fc7cd27baa7304" ON "wallets"  ("businessId", "currency") `);
        await queryRunner.query(`CREATE TYPE "public"."settlements_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_paymentsource_enum" AS ENUM('VIRTUAL_ACCOUNT_COLLECTION', 'CLEVIX_WALLET', 'POS_COLLECTION', 'USSD', 'DEBIT_CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_settlementtype_enum" AS ENUM('INSTANT', 'T+1')`);
        await queryRunner.query(`CREATE TYPE "public"."settlements_status_enum" AS ENUM('UNSETTLED', 'QUEUED', 'PROCESSING', 'SETTLED')`);
        await queryRunner.query(`CREATE TABLE "settlements" ("businessId" uuid NOT NULL, "environment" "public"."settlements_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "settlementId" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymentSource" "public"."settlements_paymentsource_enum" NOT NULL, "expectedSettledAmount" bigint NOT NULL, "settlementDate" date NOT NULL, "settlementType" "public"."settlements_settlementtype_enum" NOT NULL, "settledAmount" bigint NOT NULL DEFAULT '0', "settledAt" TIMESTAMP WITH TIME ZONE, "status" "public"."settlements_status_enum" NOT NULL DEFAULT 'UNSETTLED', CONSTRAINT "PK_0796ab0aa1eee7881d136750d5a" PRIMARY KEY ("settlementId"))`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_transactions_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_transactions_paymentsource_enum" AS ENUM('VIRTUAL_ACCOUNT_COLLECTION', 'CLEVIX_WALLET', 'POS_COLLECTION', 'USSD', 'DEBIT_CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_transactions_settlementtype_enum" AS ENUM('INSTANT', 'T+1')`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_transactions_status_enum" AS ENUM('UNSETTLED', 'QUEUED', 'PROCESSING', 'SETTLED')`);
        await queryRunner.query(`CREATE TABLE "settlement_transactions" ("businessId" uuid NOT NULL, "environment" "public"."settlement_transactions_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "settlementTransactionsId" uuid NOT NULL DEFAULT uuid_generate_v4(), "settlementId" uuid, "paymentSource" "public"."settlement_transactions_paymentsource_enum" NOT NULL, "expectedSettledAmount" bigint NOT NULL, "settlementDate" date NOT NULL, "settlementType" "public"."settlement_transactions_settlementtype_enum" NOT NULL, "settledAmount" bigint NOT NULL DEFAULT '0', "settledAt" TIMESTAMP WITH TIME ZONE, "settlementbankAccountId" uuid, "walletId" uuid, "status" "public"."settlement_transactions_status_enum" NOT NULL DEFAULT 'UNSETTLED', CONSTRAINT "PK_222385911e5048ee8d7fb68eb55" PRIMARY KEY ("settlementTransactionsId"))`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_payout_attempts_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_payout_attempts_status_enum" AS ENUM('PENDING', 'PROCESSING', 'PENDING_CONFIRMATION', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "settlement_payout_attempts" ("businessId" uuid NOT NULL, "environment" "public"."settlement_payout_attempts_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "payoutAttemptId" uuid NOT NULL DEFAULT uuid_generate_v4(), "settlementTransactionsId" uuid NOT NULL, "provider" character varying NOT NULL, "reference" character varying NOT NULL, "providerReference" character varying, "amount" bigint NOT NULL, "currency" character varying(3) NOT NULL, "destinationAccountNumber" character varying NOT NULL, "destinationAccountName" character varying NOT NULL, "destinationBankCode" character varying NOT NULL, "status" "public"."settlement_payout_attempts_status_enum" NOT NULL DEFAULT 'PENDING', "failureReason" text, "requestedAt" TIMESTAMP WITH TIME ZONE, "confirmedAt" TIMESTAMP WITH TIME ZONE, "rawRequest" jsonb, "rawResponse" jsonb, "metadata" jsonb, CONSTRAINT "PK_49c29deacf5b6199191eed19918" PRIMARY KEY ("payoutAttemptId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_361222293d9ffb5a9cd0bb2fd9" ON "settlement_payout_attempts"  ("provider", "reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b939c80a55b79f9e12f6be8a8" ON "settlement_payout_attempts"  ("settlementTransactionsId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_source_enum" AS ENUM('COLLECTION_FEE', 'WALLET_FUNDING', 'TRANSFER', 'BILLS_PAYMENT', 'BILLS_PAYMENT_FEE', 'TRANSFER_FEE', 'STAMP_DUTY', 'CHECKOUT_INVOICE')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_collectionchannel_enum" AS ENUM('VIRTUAL_ACCOUNT_COLLECTION', 'POS_COLLECTION', 'DEBIT_CARD_COLLECTION', 'CLEVIX_WALLET', 'USSD')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_executionstatus_enum" AS ENUM('INITIATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_settlementstatus_enum" AS ENUM('UNSETTLED', 'SETTLED', 'REVERSED')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_riskstatus_enum" AS ENUM('CLEAR', 'HELD', 'DISPUTED')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_direction_enum" AS ENUM('DEBIT', 'CREDIT')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("businessId" uuid NOT NULL, "environment" "public"."transactions_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "transactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid, "expectedAmount" bigint NOT NULL, "settledAmount" bigint NOT NULL, "fee" bigint NOT NULL DEFAULT '0', "source" "public"."transactions_source_enum" NOT NULL, "collectionChannel" "public"."transactions_collectionchannel_enum", "reference" character varying NOT NULL, "remark" character varying NOT NULL, "sourceId" uuid, "currency" character varying NOT NULL, "provider" character varying NOT NULL, "executionStatus" "public"."transactions_executionstatus_enum" NOT NULL, "merchantReference" character varying, "providerReference" character varying, "settlementStatus" "public"."transactions_settlementstatus_enum", "riskStatus" "public"."transactions_riskstatus_enum", "direction" "public"."transactions_direction_enum" NOT NULL, "failureReason" text, "idempotencyKey" character varying, "metadata" jsonb, CONSTRAINT "UQ_dd85cc865e0c3d5d4be095d3f3f" UNIQUE ("reference"), CONSTRAINT "UQ_86238dd0ae2d79be941104a5842" UNIQUE ("idempotencyKey"), CONSTRAINT "PK_1eb69759461752029252274c105" PRIMARY KEY ("transactionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."settlement_transaction_items_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "settlement_transaction_items" ("businessId" uuid NOT NULL, "environment" "public"."settlement_transaction_items_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "settlementTransactionItemId" uuid NOT NULL DEFAULT uuid_generate_v4(), "settlementTransactionsId" uuid NOT NULL, "transactionId" uuid NOT NULL, "amount" bigint NOT NULL, "metadata" jsonb, CONSTRAINT "UQ_54439b9581b0d46e2b4ee96e1cc" UNIQUE ("settlementTransactionsId", "transactionId"), CONSTRAINT "PK_74c20d990831260ebd332198998" PRIMARY KEY ("settlementTransactionItemId"))`);
        await queryRunner.query(`CREATE TYPE "public"."tax_settlement_destinations_destinationtype_enum" AS ENUM('BANK_ACCOUNT', 'WALLET', 'GOVERNMENT_DIRECT')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_settlement_destinations_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "tax_settlement_destinations" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "taxSettlementDestinationId" uuid NOT NULL DEFAULT uuid_generate_v4(), "taxId" uuid NOT NULL, "destinationType" "public"."tax_settlement_destinations_destinationtype_enum" NOT NULL, "settlementBankAccountId" uuid, "walletId" uuid, "providerRevenueCode" character varying, "governmentAgencyCode" character varying, "status" "public"."tax_settlement_destinations_status_enum" NOT NULL DEFAULT 'ACTIVE', "metadata" jsonb, CONSTRAINT "PK_04ea513681d503dc912a68e10a4" PRIMARY KEY ("taxSettlementDestinationId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05dcfd3c959dbf5f7ecff8828f" ON "tax_settlement_destinations"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8818bc19f6de26695de4c072cd" ON "tax_settlement_destinations"  ("destinationType") `);
        await queryRunner.query(`CREATE INDEX "IDX_841c4eb67a7971c86b5ab168e2" ON "tax_settlement_destinations"  ("taxId") `);
        await queryRunner.query(`CREATE TYPE "public"."tax_transactions_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_transactions_collectionmode_enum" AS ENUM('PLATFORM_WITHHELD', 'MERCHANT_REMITTED', 'GOVERNMENT_DIRECT')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_transactions_payer_enum" AS ENUM('CUSTOMER', 'BUSINESS')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_transactions_destinationtype_enum" AS ENUM('BANK_ACCOUNT', 'WALLET', 'GOVERNMENT_DIRECT')`);
        await queryRunner.query(`CREATE TYPE "public"."tax_transactions_status_enum" AS ENUM('ASSESSED', 'COLLECTED', 'REMITTED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "tax_transactions" ("businessId" uuid NOT NULL, "environment" "public"."tax_transactions_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "taxTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "taxId" uuid NOT NULL, "invoiceId" uuid NOT NULL, "invoiceItemId" uuid NOT NULL, "itemId" uuid NOT NULL, "transactionId" uuid, "baseAmount" bigint NOT NULL, "taxAmount" bigint NOT NULL, "rate" numeric(10,4) NOT NULL, "collectionMode" "public"."tax_transactions_collectionmode_enum" NOT NULL, "payer" "public"."tax_transactions_payer_enum" NOT NULL, "taxSettlementDestinationId" uuid, "destinationType" "public"."tax_transactions_destinationtype_enum", "settlementBankAccountId" uuid, "walletId" uuid, "providerRevenueCode" character varying, "governmentAgencyCode" character varying, "status" "public"."tax_transactions_status_enum" NOT NULL DEFAULT 'ASSESSED', "collectedAt" TIMESTAMP WITH TIME ZONE, "remittedAt" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, CONSTRAINT "PK_c42f775ec8d9c5c352ae320ee8a" PRIMARY KEY ("taxTransactionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e91389024dab9a4b2d9406278a" ON "tax_transactions"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef6bc81a5c9336fec6f7808f85" ON "tax_transactions"  ("taxId") `);
        await queryRunner.query(`CREATE INDEX "IDX_71026916af9354080f7af7b101" ON "tax_transactions"  ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_766669284870df6b3f5ebf87e6" ON "tax_transactions"  ("invoiceItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2cd3400a614006f31c4a1de5f" ON "tax_transactions"  ("invoiceId") `);
        await queryRunner.query(`CREATE TABLE "transaction_fees" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "transactionFeeId" uuid NOT NULL DEFAULT uuid_generate_v4(), "transactionId" uuid NOT NULL, "businessId" uuid NOT NULL, "provider" character varying NOT NULL, "feeSource" character varying NOT NULL, "grossAmount" bigint NOT NULL DEFAULT '0', "chargedFee" bigint NOT NULL DEFAULT '0', "providerFee" bigint NOT NULL DEFAULT '0', "platformRevenue" bigint NOT NULL DEFAULT '0', CONSTRAINT "PK_4cc09d3a691ae723c10bf8ff009" PRIMARY KEY ("transactionFeeId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_transaction_fees_transaction_source" ON "transaction_fees"  ("transactionId", "feeSource") `);
        await queryRunner.query(`CREATE TYPE "public"."webhook_snapshots_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "webhook_snapshots" ("businessId" uuid NOT NULL, "environment" "public"."webhook_snapshots_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "snapshotId" uuid NOT NULL DEFAULT uuid_generate_v4(), "webhookId" uuid NOT NULL, "transactionId" uuid, "type" character varying NOT NULL, "payload" jsonb NOT NULL, "responseStatus" integer, "responseBody" jsonb, "errorMessage" text, "deliveryStatus" character varying NOT NULL, "attempt" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_d5ae530de3b29ef1cd78fa5835d" PRIMARY KEY ("snapshotId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_snapshots_transaction" ON "webhook_snapshots"  ("businessId", "environment", "transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_snapshots_webhook_createdAt" ON "webhook_snapshots"  ("webhookId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."webhooks_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TABLE "webhooks" ("businessId" uuid NOT NULL, "environment" "public"."webhooks_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "webhookId" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "type" character varying NOT NULL, "authType" character varying NOT NULL DEFAULT 'NO_AUTH', "secret" character varying, CONSTRAINT "PK_b113650895611f034cbb9e63e60" PRIMARY KEY ("webhookId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_webhooks_business_environment_type" ON "webhooks"  ("businessId", "environment", "type") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."card_transactions_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."card_transactions_authorizationtype_enum" AS ENUM('REDIRECT_URL', 'OTP_VALIDATE')`);
        await queryRunner.query(`CREATE TYPE "public"."card_transactions_status_enum" AS ENUM('INITIATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "card_transactions" ("businessId" uuid NOT NULL, "environment" "public"."card_transactions_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "cardTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" bigint NOT NULL, "feeCharged" bigint, "cardType" character varying, "authorizationType" "public"."card_transactions_authorizationtype_enum", "status" "public"."card_transactions_status_enum" NOT NULL DEFAULT 'INITIATED', "reference" character varying NOT NULL, CONSTRAINT "UQ_09a916ae33bd32529a17899012d" UNIQUE ("reference"), CONSTRAINT "PK_4bb12110cfc5358041a77539e04" PRIMARY KEY ("cardTransactionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."collections_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."collections_source_enum" AS ENUM('POS', 'DEBIT_MANDATES', 'VIRTUAL_ACCOUNT', 'CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."collections_status_enum" AS ENUM('INITIATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "collections" ("businessId" uuid NOT NULL, "environment" "public"."collections_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "collectionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "senderBank" character varying, "bankCode" character varying, "currency" character varying NOT NULL, "amount" bigint NOT NULL, "source" "public"."collections_source_enum" NOT NULL, "reference" character varying NOT NULL, "provider" character varying NOT NULL, "status" "public"."collections_status_enum" NOT NULL, "transactionId" character varying, "sessionId" character varying, "metadata" jsonb, CONSTRAINT "PK_439ce999fe0130001a2015c3eb1" PRIMARY KEY ("collectionId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f2acf3e2a223189eddd4bccc91" ON "collections"  ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."pos_transactions_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."pos_transactions_purpose_enum" AS ENUM('WALLET_FUNDING', 'PURCHASE')`);
        await queryRunner.query(`CREATE TYPE "public"."pos_transactions_status_enum" AS ENUM('INITIATED', 'PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "pos_transactions" ("businessId" uuid NOT NULL, "environment" "public"."pos_transactions_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "posTransactionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantIdentifier" character varying, "purpose" "public"."pos_transactions_purpose_enum", "terminalSerialNumber" character varying, "accountOrItemId" character varying, "rrn" character varying NOT NULL, "stan" character varying NOT NULL, "amount" bigint NOT NULL, "reference" character varying NOT NULL, "lastFour" character varying, "firstSixDigit" character varying, "status" "public"."pos_transactions_status_enum" NOT NULL, "cardType" character varying, "terminalId" character varying, "description" character varying, CONSTRAINT "PK_1ec25bfa4bb0262949123ade8cf" PRIMARY KEY ("posTransactionId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fb9d3332a3be515da6b2417475" ON "pos_transactions"  ("rrn") `);
        await queryRunner.query(`CREATE INDEX "IDX_9403c4ac9dc7e4814c28b716ae" ON "pos_transactions"  ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."terminals_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."terminals_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "terminals" ("businessId" uuid NOT NULL, "environment" "public"."terminals_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "terminalId" uuid NOT NULL DEFAULT uuid_generate_v4(), "serialNumber" character varying NOT NULL, "provider" character varying NOT NULL, "providerTerminalId" character varying, "status" "public"."terminals_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "UQ_22d4b9ab06b235e1e79420cce39" UNIQUE ("providerTerminalId"), CONSTRAINT "PK_e4b9d808ae07e849cc071a5c5b8" PRIMARY KEY ("terminalId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6081e1ff1cd417b1941434ab78" ON "terminals"  ("serialNumber") `);
        await queryRunner.query(`CREATE TYPE "public"."dynamic_virtual_accounts_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."dynamic_virtual_accounts_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "dynamic_virtual_accounts" ("businessId" uuid NOT NULL, "environment" "public"."dynamic_virtual_accounts_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "dvaId" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountNumber" character varying NOT NULL, "status" "public"."dynamic_virtual_accounts_status_enum" NOT NULL DEFAULT 'ACTIVE', "provider" character varying NOT NULL, "merchantReference" character varying(100) NOT NULL, "reference" character varying NOT NULL, "validityTime" integer NOT NULL DEFAULT '2400', "feeCharged" bigint, CONSTRAINT "PK_b6884613a036dfed7ea97157867" PRIMARY KEY ("dvaId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9cc2161923f9d2590c64d7b8de" ON "dynamic_virtual_accounts"  ("merchantReference") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_84bf568e6035977b73568003bc" ON "dynamic_virtual_accounts"  ("reference") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_617e40e601e1904cf16d5d91bd" ON "dynamic_virtual_accounts"  ("accountNumber", "provider") WHERE "status" = 'ACTIVE'`);
        await queryRunner.query(`CREATE TYPE "public"."static_account_wallets_environment_enum" AS ENUM('TEST', 'LIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."static_account_wallets_accounttype_enum" AS ENUM('INDIVIDUAL', 'CORPORATE')`);
        await queryRunner.query(`CREATE TABLE "static_account_wallets" ("businessId" uuid NOT NULL, "environment" "public"."static_account_wallets_environment_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "walletAccountId" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountNumber" character varying NOT NULL, "accountName" character varying NOT NULL, "accountType" "public"."static_account_wallets_accounttype_enum" NOT NULL, "provider" character varying NOT NULL, "address" character varying, "bvn" character varying, "nin" character varying, "rcNumber" character varying, CONSTRAINT "PK_8f171e18f09697b2602a51cede1" PRIMARY KEY ("walletAccountId"))`);
        await queryRunner.query(`ALTER TABLE "local_governments" ADD CONSTRAINT "FK_355cac8ab6d97fe182db5818a84" FOREIGN KEY ("stateId") REFERENCES "states"("stateId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "states" ADD CONSTRAINT "FK_76ac7edf8f44e80dff569db7321" FOREIGN KEY ("countryId") REFERENCES "countries"("countryId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_8b976b1584277b9031082558607" FOREIGN KEY ("countryId") REFERENCES "countries"("countryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_25b614e2a1f6c6f01be617594ba" FOREIGN KEY ("stateId") REFERENCES "states"("stateId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_7f17de75a462ed63a8180f35fc8" FOREIGN KEY ("lgId") REFERENCES "local_governments"("lgId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_information" ADD CONSTRAINT "FK_39eb4eae73174c9cdbf595b8685" FOREIGN KEY ("businessId") REFERENCES "businesses"("businessId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permissions" ADD CONSTRAINT "FK_537129dbd8ad84161097d574f25" FOREIGN KEY ("roleId") REFERENCES "business_roles"("roleId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_role_permissions" ADD CONSTRAINT "FK_715feb0cb44e011b43558cf5e7a" FOREIGN KEY ("permissionId") REFERENCES "permissions"("permissionId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_roles" ADD CONSTRAINT "FK_4d001189dfadacd92a17dda8d41" FOREIGN KEY ("businessId") REFERENCES "businesses"("businessId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_members" ADD CONSTRAINT "FK_72a694a5cb3f8f3c49083d845a3" FOREIGN KEY ("businessId") REFERENCES "businesses"("businessId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_members" ADD CONSTRAINT "FK_785e099f43abbd887c1b93f300e" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_members" ADD CONSTRAINT "FK_f24cad0249b8e5638599d9c41cb" FOREIGN KEY ("roleId") REFERENCES "business_roles"("roleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_members" ADD CONSTRAINT "FK_b093eee860fb99a5c86f9bd97f5" FOREIGN KEY ("invitedByUserId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_fee_configuration" ADD CONSTRAINT "FK_23398b21aac00b0cb956744d104" FOREIGN KEY ("platformFeeId") REFERENCES "platform_fee_configuration"("platformFeeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "keys" ADD CONSTRAINT "FK_660d9a956a31f083fe80b189837" FOREIGN KEY ("businessId") REFERENCES "businesses"("businessId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_56bda873db7ab15b399b24e3463" FOREIGN KEY ("ledgerTransactionId") REFERENCES "ledger_transactions"("ledgerTransactionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_ab49175bf36bc26d8d1f685b4b3" FOREIGN KEY ("ledgerAccountId") REFERENCES "ledger_accounts"("ledgerAccountId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organisation_form_options" ADD CONSTRAINT "FK_02a04d365c0ff965344c8995d94" FOREIGN KEY ("customFormFormId") REFERENCES "organisation_custom_forms"("formId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organisation_custom_forms" ADD CONSTRAINT "FK_3de229239047decd143f38e757b" FOREIGN KEY ("ownerId") REFERENCES "organization_services"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_payment_transactions" ADD CONSTRAINT "FK_016b8700114cd5e5b74d9dbf13b" FOREIGN KEY ("invoiceReference") REFERENCES "organisation_invoices"("reference") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_configurations" ADD CONSTRAINT "FK_0f3ae6d1a0651de752624707f2c" FOREIGN KEY ("countryId") REFERENCES "countries"("countryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_configurations" ADD CONSTRAINT "FK_1a507a3b9751e4a27a319bb20d0" FOREIGN KEY ("stateId") REFERENCES "states"("stateId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_configurations" ADD CONSTRAINT "FK_6f6640e3b199ca3435df76c52d1" FOREIGN KEY ("lgId") REFERENCES "local_governments"("lgId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_items" ADD CONSTRAINT "FK_74d88d206c90b27d00e493891e9" FOREIGN KEY ("taxId") REFERENCES "tax_configurations"("taxId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_items" ADD CONSTRAINT "FK_3ab22878adad413258d55e5a619" FOREIGN KEY ("serviceServiceId") REFERENCES "organization_services"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_77a7964c6d5c3206763596c10f8" FOREIGN KEY ("taxId") REFERENCES "tax_configurations"("taxId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59" FOREIGN KEY ("invoiceId") REFERENCES "organisation_invoices"("invoiceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_fa3401d21f40e33ebd8b6931040" FOREIGN KEY ("itemId") REFERENCES "service_items"("itemId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organisation_invoices" ADD CONSTRAINT "FK_4f5103b10444f29651fcb56695e" FOREIGN KEY ("serviceId") REFERENCES "organization_services"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_services" ADD CONSTRAINT "FK_cf970eb883389312269fa0e76e7" FOREIGN KEY ("paymentRuleId") REFERENCES "organisation_payment_rules"("paymentRuleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banks" ADD CONSTRAINT "FK_64c5668b1ffaa284487b81da2d1" FOREIGN KEY ("countryId") REFERENCES "countries"("countryId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SettlementBankAccounts" ADD CONSTRAINT "FK_22b490f72bbeff4e5c1116238e2" FOREIGN KEY ("providerbankId") REFERENCES "banks"("bankId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlement_transactions" ADD CONSTRAINT "FK_955780ba80b64b685108f8bf735" FOREIGN KEY ("settlementId") REFERENCES "settlements"("settlementId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlement_transactions" ADD CONSTRAINT "FK_b8714ebae1ce51bc460a95e6009" FOREIGN KEY ("settlementbankAccountId") REFERENCES "SettlementBankAccounts"("bankAccountId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlement_transactions" ADD CONSTRAINT "FK_15ba1083cb1dfef2d3b264934e0" FOREIGN KEY ("walletId") REFERENCES "wallets"("walletId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlement_payout_attempts" ADD CONSTRAINT "FK_dbae85f55ba08bdd5e14ef505b7" FOREIGN KEY ("settlementTransactionsId") REFERENCES "settlement_transactions"("settlementTransactionsId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_a88f466d39796d3081cf96e1b66" FOREIGN KEY ("walletId") REFERENCES "wallets"("walletId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlement_transaction_items" ADD CONSTRAINT "FK_1bc1a6e743d87ddef7bc48428eb" FOREIGN KEY ("settlementTransactionsId") REFERENCES "settlement_transactions"("settlementTransactionsId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlement_transaction_items" ADD CONSTRAINT "FK_875f082a004874e1c3bff29a700" FOREIGN KEY ("transactionId") REFERENCES "transactions"("transactionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_settlement_destinations" ADD CONSTRAINT "FK_841c4eb67a7971c86b5ab168e2a" FOREIGN KEY ("taxId") REFERENCES "tax_configurations"("taxId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_settlement_destinations" ADD CONSTRAINT "FK_b56cd20f0beb96614e85a9d4e63" FOREIGN KEY ("settlementBankAccountId") REFERENCES "SettlementBankAccounts"("bankAccountId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_settlement_destinations" ADD CONSTRAINT "FK_c3d00afd4e34a820df9e73c97f1" FOREIGN KEY ("walletId") REFERENCES "wallets"("walletId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" ADD CONSTRAINT "FK_ef6bc81a5c9336fec6f7808f85f" FOREIGN KEY ("taxId") REFERENCES "tax_configurations"("taxId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" ADD CONSTRAINT "FK_0ca8aa18b6a0185c71cc9dbd047" FOREIGN KEY ("taxSettlementDestinationId") REFERENCES "tax_settlement_destinations"("taxSettlementDestinationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" ADD CONSTRAINT "FK_573f7103d221e22ba73f6f5d0d1" FOREIGN KEY ("settlementBankAccountId") REFERENCES "SettlementBankAccounts"("bankAccountId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" ADD CONSTRAINT "FK_a89b1c7e3137905e8af38badf9f" FOREIGN KEY ("walletId") REFERENCES "wallets"("walletId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_snapshots" ADD CONSTRAINT "FK_9253747f6838f918a7594139eda" FOREIGN KEY ("webhookId") REFERENCES "webhooks"("webhookId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "static_account_wallets" ADD CONSTRAINT "FK_4e6450ae7bae9cdd3375b96c947" FOREIGN KEY ("businessId") REFERENCES "businesses"("businessId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "static_account_wallets" DROP CONSTRAINT "FK_4e6450ae7bae9cdd3375b96c947"`);
        await queryRunner.query(`ALTER TABLE "webhook_snapshots" DROP CONSTRAINT "FK_9253747f6838f918a7594139eda"`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" DROP CONSTRAINT "FK_a89b1c7e3137905e8af38badf9f"`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" DROP CONSTRAINT "FK_573f7103d221e22ba73f6f5d0d1"`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" DROP CONSTRAINT "FK_0ca8aa18b6a0185c71cc9dbd047"`);
        await queryRunner.query(`ALTER TABLE "tax_transactions" DROP CONSTRAINT "FK_ef6bc81a5c9336fec6f7808f85f"`);
        await queryRunner.query(`ALTER TABLE "tax_settlement_destinations" DROP CONSTRAINT "FK_c3d00afd4e34a820df9e73c97f1"`);
        await queryRunner.query(`ALTER TABLE "tax_settlement_destinations" DROP CONSTRAINT "FK_b56cd20f0beb96614e85a9d4e63"`);
        await queryRunner.query(`ALTER TABLE "tax_settlement_destinations" DROP CONSTRAINT "FK_841c4eb67a7971c86b5ab168e2a"`);
        await queryRunner.query(`ALTER TABLE "settlement_transaction_items" DROP CONSTRAINT "FK_875f082a004874e1c3bff29a700"`);
        await queryRunner.query(`ALTER TABLE "settlement_transaction_items" DROP CONSTRAINT "FK_1bc1a6e743d87ddef7bc48428eb"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_a88f466d39796d3081cf96e1b66"`);
        await queryRunner.query(`ALTER TABLE "settlement_payout_attempts" DROP CONSTRAINT "FK_dbae85f55ba08bdd5e14ef505b7"`);
        await queryRunner.query(`ALTER TABLE "settlement_transactions" DROP CONSTRAINT "FK_15ba1083cb1dfef2d3b264934e0"`);
        await queryRunner.query(`ALTER TABLE "settlement_transactions" DROP CONSTRAINT "FK_b8714ebae1ce51bc460a95e6009"`);
        await queryRunner.query(`ALTER TABLE "settlement_transactions" DROP CONSTRAINT "FK_955780ba80b64b685108f8bf735"`);
        await queryRunner.query(`ALTER TABLE "SettlementBankAccounts" DROP CONSTRAINT "FK_22b490f72bbeff4e5c1116238e2"`);
        await queryRunner.query(`ALTER TABLE "banks" DROP CONSTRAINT "FK_64c5668b1ffaa284487b81da2d1"`);
        await queryRunner.query(`ALTER TABLE "organization_services" DROP CONSTRAINT "FK_cf970eb883389312269fa0e76e7"`);
        await queryRunner.query(`ALTER TABLE "organisation_invoices" DROP CONSTRAINT "FK_4f5103b10444f29651fcb56695e"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_fa3401d21f40e33ebd8b6931040"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_7fb6895fc8fad9f5200e91abb59"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_77a7964c6d5c3206763596c10f8"`);
        await queryRunner.query(`ALTER TABLE "service_items" DROP CONSTRAINT "FK_3ab22878adad413258d55e5a619"`);
        await queryRunner.query(`ALTER TABLE "service_items" DROP CONSTRAINT "FK_74d88d206c90b27d00e493891e9"`);
        await queryRunner.query(`ALTER TABLE "tax_configurations" DROP CONSTRAINT "FK_6f6640e3b199ca3435df76c52d1"`);
        await queryRunner.query(`ALTER TABLE "tax_configurations" DROP CONSTRAINT "FK_1a507a3b9751e4a27a319bb20d0"`);
        await queryRunner.query(`ALTER TABLE "tax_configurations" DROP CONSTRAINT "FK_0f3ae6d1a0651de752624707f2c"`);
        await queryRunner.query(`ALTER TABLE "invoice_payment_transactions" DROP CONSTRAINT "FK_016b8700114cd5e5b74d9dbf13b"`);
        await queryRunner.query(`ALTER TABLE "organisation_custom_forms" DROP CONSTRAINT "FK_3de229239047decd143f38e757b"`);
        await queryRunner.query(`ALTER TABLE "organisation_form_options" DROP CONSTRAINT "FK_02a04d365c0ff965344c8995d94"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_ab49175bf36bc26d8d1f685b4b3"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_56bda873db7ab15b399b24e3463"`);
        await queryRunner.query(`ALTER TABLE "keys" DROP CONSTRAINT "FK_660d9a956a31f083fe80b189837"`);
        await queryRunner.query(`ALTER TABLE "business_fee_configuration" DROP CONSTRAINT "FK_23398b21aac00b0cb956744d104"`);
        await queryRunner.query(`ALTER TABLE "business_members" DROP CONSTRAINT "FK_b093eee860fb99a5c86f9bd97f5"`);
        await queryRunner.query(`ALTER TABLE "business_members" DROP CONSTRAINT "FK_f24cad0249b8e5638599d9c41cb"`);
        await queryRunner.query(`ALTER TABLE "business_members" DROP CONSTRAINT "FK_785e099f43abbd887c1b93f300e"`);
        await queryRunner.query(`ALTER TABLE "business_members" DROP CONSTRAINT "FK_72a694a5cb3f8f3c49083d845a3"`);
        await queryRunner.query(`ALTER TABLE "business_roles" DROP CONSTRAINT "FK_4d001189dfadacd92a17dda8d41"`);
        await queryRunner.query(`ALTER TABLE "business_role_permissions" DROP CONSTRAINT "FK_715feb0cb44e011b43558cf5e7a"`);
        await queryRunner.query(`ALTER TABLE "business_role_permissions" DROP CONSTRAINT "FK_537129dbd8ad84161097d574f25"`);
        await queryRunner.query(`ALTER TABLE "business_information" DROP CONSTRAINT "FK_39eb4eae73174c9cdbf595b8685"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_7f17de75a462ed63a8180f35fc8"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_25b614e2a1f6c6f01be617594ba"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_8b976b1584277b9031082558607"`);
        await queryRunner.query(`ALTER TABLE "states" DROP CONSTRAINT "FK_76ac7edf8f44e80dff569db7321"`);
        await queryRunner.query(`ALTER TABLE "local_governments" DROP CONSTRAINT "FK_355cac8ab6d97fe182db5818a84"`);
        await queryRunner.query(`DROP TABLE "static_account_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."static_account_wallets_accounttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."static_account_wallets_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_617e40e601e1904cf16d5d91bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84bf568e6035977b73568003bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cc2161923f9d2590c64d7b8de"`);
        await queryRunner.query(`DROP TABLE "dynamic_virtual_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."dynamic_virtual_accounts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."dynamic_virtual_accounts_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6081e1ff1cd417b1941434ab78"`);
        await queryRunner.query(`DROP TABLE "terminals"`);
        await queryRunner.query(`DROP TYPE "public"."terminals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."terminals_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9403c4ac9dc7e4814c28b716ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb9d3332a3be515da6b2417475"`);
        await queryRunner.query(`DROP TABLE "pos_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."pos_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pos_transactions_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pos_transactions_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2acf3e2a223189eddd4bccc91"`);
        await queryRunner.query(`DROP TABLE "collections"`);
        await queryRunner.query(`DROP TYPE "public"."collections_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."collections_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."collections_environment_enum"`);
        await queryRunner.query(`DROP TABLE "card_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."card_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."card_transactions_authorizationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."card_transactions_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhooks_business_environment_type"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`DROP TYPE "public"."webhooks_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhook_snapshots_webhook_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhook_snapshots_transaction"`);
        await queryRunner.query(`DROP TABLE "webhook_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_snapshots_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transaction_fees_transaction_source"`);
        await queryRunner.query(`DROP TABLE "transaction_fees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2cd3400a614006f31c4a1de5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_766669284870df6b3f5ebf87e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71026916af9354080f7af7b101"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef6bc81a5c9336fec6f7808f85"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e91389024dab9a4b2d9406278a"`);
        await queryRunner.query(`DROP TABLE "tax_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."tax_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_transactions_destinationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_transactions_payer_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_transactions_collectionmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_transactions_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_841c4eb67a7971c86b5ab168e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8818bc19f6de26695de4c072cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05dcfd3c959dbf5f7ecff8828f"`);
        await queryRunner.query(`DROP TABLE "tax_settlement_destinations"`);
        await queryRunner.query(`DROP TYPE "public"."tax_settlement_destinations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_settlement_destinations_destinationtype_enum"`);
        await queryRunner.query(`DROP TABLE "settlement_transaction_items"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_transaction_items_environment_enum"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_riskstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_settlementstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_executionstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_collectionchannel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b939c80a55b79f9e12f6be8a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_361222293d9ffb5a9cd0bb2fd9"`);
        await queryRunner.query(`DROP TABLE "settlement_payout_attempts"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_payout_attempts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_payout_attempts_environment_enum"`);
        await queryRunner.query(`DROP TABLE "settlement_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_transactions_settlementtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_transactions_paymentsource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlement_transactions_environment_enum"`);
        await queryRunner.query(`DROP TABLE "settlements"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_settlementtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_paymentsource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0dc7c27ca503fc7cd27baa7304"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TYPE "public"."wallets_environment_enum"`);
        await queryRunner.query(`DROP TABLE "SettlementBankAccounts"`);
        await queryRunner.query(`DROP TYPE "public"."SettlementBankAccounts_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e608c72b9dbc500479e821b695"`);
        await queryRunner.query(`DROP TABLE "banks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e2ba1a7e2a123c0382ff596ba"`);
        await queryRunner.query(`DROP TABLE "business_settlement_configs"`);
        await queryRunner.query(`DROP TYPE "public"."business_settlement_configs_settlementtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."business_settlement_configs_paymentsource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."business_settlement_configs_settlementlocation_enum"`);
        await queryRunner.query(`DROP TYPE "public"."business_settlement_configs_environment_enum"`);
        await queryRunner.query(`DROP TABLE "organization_services"`);
        await queryRunner.query(`DROP TYPE "public"."organization_services_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32365b6733883d0cec79c0938a"`);
        await queryRunner.query(`DROP TABLE "organisation_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_invoices_redemptionstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_invoices_environment_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_items_environment_enum"`);
        await queryRunner.query(`DROP TABLE "service_items"`);
        await queryRunner.query(`DROP TYPE "public"."service_items_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f3ae6d1a0651de752624707f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a507a3b9751e4a27a319bb20d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f6640e3b199ca3435df76c52d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47464f060473bf1af7084c05f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a45be23c6ab4d0aaa1076e66a4"`);
        await queryRunner.query(`DROP TABLE "tax_configurations"`);
        await queryRunner.query(`DROP TYPE "public"."tax_configurations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_configurations_payer_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tax_configurations_collectionmode_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_payment_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payment_transactions_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payment_transactions_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_payment_transactions_environment_enum"`);
        await queryRunner.query(`DROP TABLE "organisation_custom_forms"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_custom_forms_ownertype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_custom_forms_formtype_enum"`);
        await queryRunner.query(`DROP TABLE "organisation_form_options"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_form_options_environment_enum"`);
        await queryRunner.query(`DROP TABLE "organisation_payment_rules"`);
        await queryRunner.query(`DROP TYPE "public"."organisation_payment_rules_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12a06b7faf8dc50c2a7590e603"`);
        await queryRunner.query(`DROP TABLE "ledger_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_451dcefe42673ec42abb693d33"`);
        await queryRunner.query(`DROP TABLE "ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_entries_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d87ef09b49fbca993d4370616a"`);
        await queryRunner.query(`DROP TABLE "ledger_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."ledger_transactions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18d316d3f20936e7a518d696ff"`);
        await queryRunner.query(`DROP TABLE "keys"`);
        await queryRunner.query(`DROP TYPE "public"."keys_environment_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b33ba5b78af59608a0877f829"`);
        await queryRunner.query(`DROP TABLE "business_fee_configuration"`);
        await queryRunner.query(`DROP TABLE "platform_fee_configuration"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_419792071f3f329280668ca950"`);
        await queryRunner.query(`DROP TABLE "business_members"`);
        await queryRunner.query(`DROP TYPE "public"."business_members_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3be415f19162963a266cac5a92"`);
        await queryRunner.query(`DROP TABLE "business_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30d94f2130ca24db97d9d52a26"`);
        await queryRunner.query(`DROP TABLE "business_role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017943867ed5ceef9c03edd974"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "business_representatives"`);
        await queryRunner.query(`DROP TYPE "public"."business_representatives_identificationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."business_representatives_verificationstatus_enum"`);
        await queryRunner.query(`DROP TABLE "business_information"`);
        await queryRunner.query(`DROP TYPE "public"."business_information_businesstype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ac3ab3b9418ea0499239cdd82"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP TYPE "public"."businesses_kycstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dd5aa96583bb914f7bbdb3e7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa1376321185575cf2226b1491"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e0f02ae40fe2ea4da13b8d460"`);
        await queryRunner.query(`DROP TABLE "states"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5df41035b36fce1e68f1ff5fb4"`);
        await queryRunner.query(`DROP TABLE "local_governments"`);
        await queryRunner.query(`DROP TABLE "business_documents"`);
        await queryRunner.query(`DROP TYPE "public"."business_documents_verificationstatus_enum"`);
    }

}
