export enum LedgerAccountOwnerType {
  BUSINESS = 'BUSINESS',
  SYSTEM = 'SYSTEM',
  PROVIDER = 'PROVIDER',
}

export enum LedgerAccountType {
  CUSTOMER_CASH = 'CUSTOMER_CASH',
  PENDING_COLLECTION = 'PENDING_COLLECTION',
  SETTLEMENT_PAYABLE = 'SETTLEMENT_PAYABLE',
  PROVIDER_SETTLEMENT = 'PROVIDER_SETTLEMENT',
  PROVIDER_FEE_EXPENSE = 'PROVIDER_FEE_EXPENSE',
  FEES_REVENUE = 'FEES_REVENUE',
  PAYOUTS_CLEARING = 'PAYOUTS_CLEARING',
  CHARGEBACKS = 'CHARGEBACKS',
}

export enum LedgerEntryDirection {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum LedgerTransactionStatus {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
}
