export enum BusinessMemberRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  DEVELOPER = 'DEVELOPER',
  FINANCE = 'FINANCE',
  SUPPORT = 'SUPPORT',
  VIEWER = 'VIEWER',
}

export enum BusinessMemberStatus {
  INVITED = 'INVITED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REMOVED = 'REMOVED',
}

export enum PermissionsEnum {
  KEY_VIEW = 'KEY_VIEW',
  KEY_CREATE = 'KEY_CREATE',
  WEBHOOK_VIEW = 'WEBHOOK_VIEW',
  WEBHOOK_CREATE = 'WEBHOOK_CREATE',
  WEBHOOK_UPDATE = 'WEBHOOK_UPDATE',
  WEBHOOK_DELETE = 'WEBHOOK_DELETE',
}
